name: Main

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Deps
        run: python3 -m pip install pipenv && python3 -m pipenv install

      # Unit tests
      - name: Run Unit tests
        run: pipenv run python -m unittest discover -s ./tests -p "test_*.py"

      # Secret Scanning will not work
      # - name: Run Full Scenario (Public repo)
      #   run: |
      #     pipenv run main \
      #       --github-repository "GeekMasher/Pixi" \
      #       --github-ref "refs/heads/master" \
      #       --github-token "${{ secrets.FULL_SCOPE_TOKEN }}" \
      #       --action "continue" \
      #       --disable-secret-scanning

      # - name: Run Full Scenario (Private repo)
      #   run: |
      #     pipenv run main \
      #       --github-repository "GeekMasherOrg/Pixi" \
      #       --github-ref "refs/heads/master" \
      #       --github-token "${{ secrets.FULL_SCOPE_TOKEN }}" \
      #       --action "continue"
